#include <string>
#include <fstream>
#include <sstream>
#include <cstdio>
#include <ctype.h>
#include <cstdlib>
#include <string.h>

#include <signal.h>

#include <iocsh.h>
#include <shareLib.h>
#include <epicsExport.h>
#include <epicsReadline.h>
#include <epicsThread.h>
#include <epicsStdio.h>
#include <epicsMutex.h>
#include <epicsGuard.h>

#include "luaEpics.h"
#include "luaShell.h"

/* Lua 5.5 moved lua_writestringerror / lua_writestring / lua_writeline and
   the lua_assert debug macro out of the public headers into llimits.h.
   Upstream lua.c includes llimits.h for the same reason. */
#include "llimits.h"

#if !defined(LUA_PROGNAME)
#define LUA_PROGNAME		"lua"
#endif

#define LUA_BREAKSHELL 666

#if defined(__vxworks) || defined(vxWorks)
	#include <symLib.h>
	#include <sysSymTbl.h>
#endif

static lua_State *globalL = NULL;
static const char *progname = LUA_PROGNAME;

static epicsThreadPrivateId shellStateId = NULL;
static lua_State* default_state = NULL;
static epicsMutex defaultStateMutex;

static void ensureShellStateId(void)
{
	if (!shellStateId)    { shellStateId = epicsThreadPrivateCreate(); }
}

static void luashBody(lua_State* state, const char* pathname, const char* macros);
static int luashBegin(const char* pathname, const char* macros, lua_State* state);

/*
** Hook set by signal function to stop the interpreter.
*/
static void lstop (lua_State *L, lua_Debug *ar)
{
	(void)ar;  /* unused arg. */
	lua_sethook(L, NULL, 0, 0);  /* reset hook */
	luaL_error(L, "interrupted!");
}

/*
** Function to be called at a C signal. Because a C signal cannot
** just change a Lua state (as there is no proper synchronization),
** this function only sets a hook that, when called, will stop the
** interpreter.
*/
static void laction (int i)
{
	signal(i, SIG_DFL); /* if another SIGINT happens, terminate process */
	lua_sethook(globalL, lstop, LUA_MASKCALL | LUA_MASKRET | LUA_MASKCOUNT, 1);
}


/*
** Prints an error message, adding the program name in front of it
** (if present)
*/
static void l_message (const char *pname, const char *msg)
{
	if (pname)    { lua_writestringerror("%s: ", pname); }

	lua_writestringerror("%s\n", msg);
}


/*
** Check whether 'status' is not OK and, if so, prints the error
** message on the top of the stack. It assumes that the error object
** is a string, as it was either generated by Lua or by 'msghandler'.
*/
static int report (lua_State *L, int status)
{
	if (status != LUA_OK)
	{
		const char *msg = lua_tostring(L, -1);
		l_message(progname, msg);
		lua_pop(L, 1);  /* remove message */
	}

	return status;
}

/*
** Message handler used to run all chunks
*/
static int msghandler (lua_State *L)
{
	/* Unfortunately, we have to use the error system to perform script breaks
	 * in the shell because of how the chunks are set up. Previous, just checked
	 * if a line stated "exit", but that doesn't work within conditionals. Could
	 * use just plain "return", but that wouldn't work on the general command line.
	 * The current best option is to have "exit()" throw a specialized error that
	 * we can catch here and trigger the shell to proceede.
	 */
	if (lua_type(L, 1) == LUA_TLIGHTUSERDATA && lua_topointer(L, 1) == NULL)
	{
		return 1;
	}

	const char *msg = lua_tostring(L, 1);

	if (msg == NULL)  /* is error object not a string? */
	{
		if (luaL_callmeta(L, 1, "__tostring") &&  /* does it have a metamethod */
		    lua_type(L, -1) == LUA_TSTRING)  /* that produces a string? */
		{
			return 1;  /* that is the message */
		}
		else
		{
			msg = lua_pushfstring(L, "(error object is a %s value)", luaL_typename(L, 1));
		}
	}

	luaL_traceback(L, L, msg, 1);  /* append a standard traceback */

	return 1;  /* return the traceback */
}


/*
** Prints (calling the Lua 'print' function) any values on the stack
*/
static void l_print (lua_State *L)
{
	int n = lua_gettop(L);

	if (n > 0)  /* any result to be printed? */
	{
		luaL_checkstack(L, LUA_MINSTACK, "too many results to print");
		lua_getglobal(L, "print");
		lua_insert(L, 1);

		if (lua_pcall(L, n, 0, 0) != LUA_OK)
		{
			l_message(progname, lua_pushfstring(L, "error calling 'print' (%s)", lua_tostring(L, -1)));
		}
	}
}


/*
** Read multiple lines until a complete Lua statement
*/
static int multiline (lua_State *L, const char* prompt, void* readlineContext)
{
	const char* subprompt = prompt ? "> " : "";

	for (;;)  /* repeat until gets a complete statement */
	{
		size_t len;
		const char *buffer = lua_tolstring(L, 1, &len);  /* get what it has */
		int status = luaL_loadbuffer(L, buffer, len, "=stdin");  /* try it */

		/* cannot or should not try to add continuation line */
		if (!luaIncomplete(L, status))    { return status; }

		const char* raw = epicsReadline(subprompt, readlineContext);

		if (!raw)       { return status; }

		std::string line(raw);
		while (line.length() > 0 && isspace(line[0]))    { line.erase(0,1); }

		if (line == "exit")    { line = "exit()"; }

		if (!prompt)    { printf("%s\n", raw); }

		lua_pushstring(L, line.c_str());
		lua_pushliteral(L, "\n");  /* add newline... */
		lua_insert(L, -2);  /* ...between the two lines */
		lua_concat(L, 3);  /* join them */
	}
}


/*
** Interface to 'lua_pcall', which sets appropriate message function
** and C-signal handler. Used to run all chunks.
*/
static int docall (lua_State *L, int narg, int nres)
{
	int status;
	int base = lua_gettop(L) - narg;   /* function index */
	lua_pushcfunction(L, msghandler);  /* push message handler */
	lua_insert(L, base);               /* put it under function and args */
	globalL = L;                       /* to be available to 'laction' */
	signal(SIGINT, laction);           /* set C-signal handler */
	status = lua_pcall(L, narg, nres, base);
	signal(SIGINT, SIG_DFL);          /* reset C-signal handler */
	lua_remove(L, base);              /* remove message handler from the stack */

	if (status == LUA_ERRRUN)
	{
		if (lua_type(L, -1) == LUA_TLIGHTUSERDATA && lua_topointer(L, -1) == NULL)
		{
			return LUA_BREAKSHELL;
		}
	}

	return status;
}

static void repl(lua_State* state, void* readlineContext, const char* prompt)
{
	int status;

	while (true)
	{
		/*
		** Read a line and try to load (compile) it first as an expression (by
		** adding "return " in front of it) and second as a statement. Return
		** the final status of load/call with the resulting function (if any)
		** in the top of the stack.
		*/
		lua_settop(state, 0);

		const char* raw = epicsReadline(prompt, readlineContext);

		if (raw == NULL)     { return; }

		std::string line(raw);

		if (line.empty())    { continue; }

		// Eliminate leading white space
		while (line.length() > 0 && isspace(line[0]))    { line.erase(0,1); }

		if (line == "exit")    { line = "exit()"; }

		if (line[0] == '<')
		{
			// Get rid of < character
			line.erase(0,1);

			// Get rid of whitespace
			while (line.length() > 0 && isspace(line[0]))    { line.erase(0,1); }

			luashBody(state, line.c_str(), NULL);
			continue;
		}

		if (line[0] == '#')
		{
			lua_getglobal(state, "LEPICS_HASH_COMMENTS");
			const char* yn = lua_tostring(state, -1);
			lua_pop(state, 1);
			if (yn && std::string(yn) == "YES")
			{
				/* #- comments are silent, other # comments are echoed */
				if (prompt == NULL && (line.length() < 2 || line[1] != '-'))
				{
					printf("%s\n", raw);
				}
				continue;
			}
		}

		lua_pushstring(state, line.c_str());

		if (prompt == NULL)    { printf("%s\n", raw); }

		/* try as command, maybe with continuation lines */
		if ((status = luaAddReturn(state)) != LUA_OK)    { status = multiline(state, prompt, readlineContext); }

		lua_remove(state, 1);  /* remove line from the stack */
		lua_assert(lua_gettop(state) == 1);

		if (status == LUA_OK)     { status = docall(state, 0, LUA_MULTRET); }

		if (status == LUA_BREAKSHELL)    { return; }
		if (status == LUA_OK)            { l_print(state); }
		else                             { report(state, status); }
	}
}



/*
 * File-mode execution: reads and executes each statement with
 * line-by-line echoing (matching iocsh behavior). Multi-line
 * constructs (function/if/for/do blocks) are accumulated until
 * the statement is complete. Output from each statement appears
 * immediately after the echoed lines that produced it.
 */
static void execfile(lua_State* state, void* readlineContext)
{
	int status;

	while (true)
	{
		lua_settop(state, 0);

		const char* raw = epicsReadline(NULL, readlineContext);

		if (raw == NULL)    { return; }

		std::string line(raw);

		/* Skip empty lines (don't echo) */
		std::string trimmed(line);
		while (trimmed.length() > 0 && isspace(trimmed[0]))    { trimmed.erase(0,1); }

		if (trimmed.empty())    { continue; }

		/* Handle < include directive */
		if (trimmed[0] == '<')
		{
			printf("%s\n", raw);

			trimmed.erase(0, 1);
			while (trimmed.length() > 0 && isspace(trimmed[0]))    { trimmed.erase(0, 1); }

			if (!trimmed.empty())    { luashBody(state, trimmed.c_str(), NULL); }
			continue;
		}

		/* Handle hash comments */
		if (trimmed[0] == '#')
		{
			lua_getglobal(state, "LEPICS_HASH_COMMENTS");
			const char* yn = lua_tostring(state, -1);
			lua_pop(state, 1);
			if (yn && std::string(yn) == "YES")
			{
				/* #- comments are silent, other # comments are echoed */
				if (trimmed.length() < 2 || trimmed[1] != '-')
				{
					printf("%s\n", raw);
				}
				continue;
			}
		}

		/* Echo the line */
		printf("%s\n", raw);

		if (trimmed == "exit")    { trimmed = "exit()"; line = "exit()"; }

		lua_pushstring(state, trimmed.c_str());

		/* Try as expression first, then as statement with continuations */
		if ((status = luaAddReturn(state)) != LUA_OK)
		{
			status = multiline(state, NULL, readlineContext);
		}

		lua_remove(state, 1);  /* remove line from the stack */

		if (status == LUA_OK)     { status = docall(state, 0, LUA_MULTRET); }

		if (status == LUA_BREAKSHELL)    { return; }
		if (status == LUA_OK)            { l_print(state); }
		else                             { report(state, status); }
	}
}


static void luashBody(lua_State* state, const char* pathname, const char* macros)
{
	if (macros)    { luaLoadMacros(state, macros); }

	int wasOkToBlock;

	const char* prompt = NULL;
	void* readlineContext = NULL;

	FILE *fp = NULL;

	if (pathname)
	{
		std::string filename(pathname);
		std::string path = luaLocateFile(filename);

		if (path.empty())    { printf("File %s not found\n", pathname); return; }

		fp = fopen(path.c_str(), "r");

		readlineContext = epicsReadlineBegin(fp);
	}
	else
	{
		readlineContext = epicsReadlineBegin(NULL);

		prompt = std::getenv("LUASH_PS1");

		#if defined(__vxworks) || defined(vxWorks)
		/* For compatibility reasons look for global symbols */
		if (prompt == NULL)
		{
			char* symbol;
			SYM_TYPE type;

			if (symFindByName(sysSymTbl, "LUASH_PS1", &symbol, &type) == OK)
			{
				prompt = *(char**) symbol;
			}
		}
		#endif

		if (prompt == NULL)    { prompt = "luash> "; }
	}


	wasOkToBlock = epicsThreadIsOkToBlock();
    epicsThreadSetOkToBlock(1);

	if (readlineContext)
	{
		if (pathname)    { execfile(state, readlineContext); }
		else             { repl(state, readlineContext, prompt); }
	}
	else
	{
		printf("Couldn't allocate command-line object.\n");
	}

	if (fp)    { fclose(fp); }

	epicsThreadSetOkToBlock( wasOkToBlock);
	epicsReadlineEnd(readlineContext);
	lua_settop(state, 0);  /* clear stack */

	if (macros)    { luaPopScope(state); }
}

void spawn_thread_callback(void* arg)
{
	lua_State* state = (lua_State*) arg;

	int status = docall(state, 0, 0);

	if (status != LUA_OK)    { report(state, status); }

	luaStateUnref(state);
}

static int l_execcode(lua_State* state)
{
	lua_settop(state, 1);

	int datatype = lua_type(state, -1);

	const char* str = NULL;
	const char* in  = NULL;
	const char* out = NULL;


	/* If using named parameters, check for input/in and output/out */

	if (datatype == LUA_TTABLE)
	{
		lua_geti(state, -1, 1);
		if (!lua_isnil(state, -1))    { str = lua_tostring(state, -1); }
		lua_pop(state, 1);

		lua_getfield(state, -1, "output");
		if (!lua_isnil(state, -1))    { out = lua_tostring(state, -1); }
		lua_pop(state, 1);

		lua_getfield(state, -1, "out");
		if (!lua_isnil(state, -1))    { out = lua_tostring(state, -1); }
		lua_pop(state, 1);

		lua_getfield(state, -1, "input");
		if (!lua_isnil(state, -1))    { in = lua_tostring(state, -1); }
		lua_pop(state, 1);

		lua_getfield(state, -1, "in");
		if (!lua_isnil(state, -1))    { in = lua_tostring(state, -1); }
		lua_pop(state, 1);
	}
	else if (datatype == LUA_TSTRING)
	{
		str = lua_tostring(state, 1);
	}


	/* Output redirects */
	FILE* new_out = NULL;
	FILE* old_out = epicsGetThreadStdout();

	if (out)
	{
		new_out = fopen(out, "w");

		if (new_out == NULL)
		{
			return luaL_error(state, "Error in opening file(%s)\n", out);
		}

		epicsSetThreadStdout(new_out);
	}

	int status = LUA_OK;

	/* prioritize file input over command definition */
	if (in)        { luashBody(state, in, NULL); }
	else if (str)
	{
		status = luaL_dostring(state, str);
	}

	/* Return to previous output */
	if (out)
	{
		epicsSetThreadStdout(old_out);
		fclose(new_out);
	}

	if (status != LUA_OK)    { return luaL_error(state, "Error (%d) running string (%s)\n", status, str); }

	return 0;
}


static LUA_FUNCTION_LOAD_HOOK_ROUTINE previousFunctionHook=NULL;

static void newFunctionLoadedHook(const char* function_name, lua_CFunction function)
{
	if (previousFunctionHook)    { previousFunctionHook(function_name, function); }

	ensureShellStateId();
	lua_State* shell_state = (lua_State*) epicsThreadPrivateGet(shellStateId);
	if (shell_state)    { lua_register(shell_state, function_name, function); }
}


static const iocshArg luashCmdArg0 = { "lua shell script", iocshArgString};
static const iocshArg luashCmdArg1 = { "macros", iocshArgString};
static const iocshArg *luashCmdArgs[2] = {&luashCmdArg0, &luashCmdArg1};
static const iocshFuncDef luashFuncDef = {"luash", 2, luashCmdArgs};

static void luashCallFunc(const iocshArgBuf* args)
{
	luaDeprecated("luash", "luaShell");
	luashBegin(args[0].sval, args[1].sval, NULL);
}

static const iocshArg luaCmdCmdArg0 = { "lua script", iocshArgString};
static const iocshArg luaCmdCmdArg1 = { "macros", iocshArgString};
static const iocshArg *luaCmdCmdArgs[2] = {&luaCmdCmdArg0, &luaCmdCmdArg1};
static const iocshFuncDef luaCmdFuncDef = {"luaCmd", 2, luaCmdCmdArgs};


static void luaCmdCallFunc(const iocshArgBuf* args)
{
	luaCmd(args[0].sval, args[1].sval);
}

static const iocshArg spawnCmdArg0 = { "lua script", iocshArgString};
static const iocshArg spawnCmdArg1 = { "macros", iocshArgString};
static const iocshArg *spawnCmdArgs[2] = {&spawnCmdArg0, &spawnCmdArg1};
static const iocshFuncDef spawnFuncDef = {"luaSpawn", 2, spawnCmdArgs};

static void spawnCallFunc(const iocshArgBuf* args)
{
	luaSpawn(args[0].sval, args[1].sval);
}

static const iocshArg loadFileCmdArg0 = { "lua script", iocshArgString};
static const iocshArg loadFileCmdArg1 = { "macros", iocshArgString};
static const iocshArg *loadFileCmdArgs[2] = {&loadFileCmdArg0, &loadFileCmdArg1};
static const iocshFuncDef loadFileFuncDef = {"luaLoadFile", 2, loadFileCmdArgs};

static void loadFileCallFunc(const iocshArgBuf* args)
{
	luaLoadFile(args[0].sval, args[1].sval);
}

/* --- Canonical run/load iocsh commands (Stage 2) --- */

static const iocshArg runStringArg0 = { "lua code", iocshArgString};
static const iocshArg runStringArg1 = { "macros", iocshArgString};
static const iocshArg runStringArg2 = { "options", iocshArgString};
static const iocshArg *runStringArgs[3] = {&runStringArg0, &runStringArg1, &runStringArg2};
static const iocshFuncDef runStringFuncDef = {"luaRunString", 3, runStringArgs};

static void runStringCallFunc(const iocshArgBuf* args)
{
	luaRunString(args[0].sval, args[1].sval, args[2].sval);
}

static const iocshArg runFileArg0 = { "lua script", iocshArgString};
static const iocshArg runFileArg1 = { "macros", iocshArgString};
static const iocshArg runFileArg2 = { "options", iocshArgString};
static const iocshArg *runFileArgs[3] = {&runFileArg0, &runFileArg1, &runFileArg2};
static const iocshFuncDef runFileFuncDef = {"luaRunFile", 3, runFileArgs};

static void runFileCallFunc(const iocshArgBuf* args)
{
	luaRunFile(args[0].sval, args[1].sval, args[2].sval);
}

static const iocshArg shellArg0 = { "lua shell script", iocshArgString};
static const iocshArg shellArg1 = { "macros", iocshArgString};
static const iocshArg *shellArgs[2] = {&shellArg0, &shellArg1};
static const iocshFuncDef shellFuncDef = {"luaShell", 2, shellArgs};

static void shellCallFunc(const iocshArgBuf* args)
{
	luaShell(args[0].sval, args[1].sval);
}

static void initState(lua_State* state)
{
	luaL_getmetatable(state, "iocsh_meta");
	luaPushScope(state);

	lua_newtable(state);
	lua_setfield(state, LUA_REGISTRYINDEX, "OSI_REDIRECTS_STACK");

	lua_register(state, "exec", l_execcode);

	lua_pushlightuserdata(state, iocshPpdbbase);
	lua_setglobal(state, "pdbbase");
}


/*
 * Wrapper around the core shell loop, checks if there is already a shell running
 * to allow for nested shell calls. Otherwise, creates a new state and loads hooks
 * in case a dbd file is loaded during operation. After the shell is done running,
 * clean up the resources.
 */
static int luashBegin(const char* pathname, const char* macros, lua_State* state)
{
	ensureShellStateId();
	lua_State* shell_state = (lua_State*) epicsThreadPrivateGet(shellStateId);

	if (state)
	{
		initState(state);
		shell_state = state;
		epicsThreadPrivateSet(shellStateId, shell_state);
	}

	if (shell_state != NULL)
	{
		luashBody(shell_state, pathname, macros);
		return 0;
	}

	// Make a copy to check after finishing the script, may have changed by then
	lua_State* check_state;
	{
		epicsGuard<epicsMutex> guard(defaultStateMutex);
		check_state = default_state;
	}

	if (check_state != NULL)
	{
		shell_state = check_state;
	}
	else
	{
		shell_state = luaCreateState();
		initState(shell_state);
	}

	epicsThreadPrivateSet(shellStateId, shell_state);

	luashBody(shell_state, pathname, macros);

	if (check_state == NULL)
	{
		luaStateUnref(shell_state);
	}

	epicsThreadPrivateSet(shellStateId, NULL);

	return 0;
}


epicsShareFunc int epicsShareAPI luash(lua_State* state, const char* pathname, const char* macros)
{
	static int hookInstalled = 0;

	if (!hookInstalled)
	{
		previousFunctionHook = luaLoadFunctionHook;
		luaLoadFunctionHook = newFunctionLoadedHook;
		hookInstalled = 1;
	}
	
	return luashBegin(pathname, macros, state);
}

epicsShareFunc int epicsShareAPI luash(lua_State* state, const char* pathname)
{
	return luash(state, pathname, NULL);
}

epicsShareFunc int epicsShareAPI luaCmd(lua_State* state, const char* command, const char* macros)
{
	if (! command)    { return -1; }

	lua_State* used_environ;

	if (state)    { used_environ = state; }
	else          { used_environ = luaCreateState(); }

	luaL_getmetatable(used_environ, "iocsh_meta");
	luaPushScope(used_environ);

	if (macros)    { luaLoadMacros(used_environ, macros); }

	int status = luaL_loadbuffer(used_environ, command, strlen(command), "=stdin");

	if (status == LUA_OK)     { status = docall(used_environ, 0, LUA_MULTRET); }

	if (status == LUA_OK)     { l_print(used_environ); }
	else                      { report(used_environ, status); }

	//Pop macro scope
	if (macros)    { luaPopScope(used_environ); }

	//Pop iocsh_meta scope
	luaPopScope(used_environ);

	if (!state)    { luaStateUnref(used_environ); }

	return 0;
}

extern "C"
{

/*
 * Epics function to call the shell
 */
epicsShareFunc int epicsShareAPI luash(const char* pathname)
{
	luaDeprecated("luash", "luaShell");
	return luash(NULL, pathname, NULL);
}

epicsShareFunc int epicsShareAPI luashLoad(const char* pathname, const char* macros)
{
	luaDeprecated("luashLoad", "luaShell");
	return luash(NULL, pathname, macros);
}

/*
 * Epics function for one-liner lua commands
 */
epicsShareFunc int epicsShareAPI luaCmd(const char* command, const char* macros)
{
	luaDeprecated("luaCmd", "luaRunString");
	return luaCmd(NULL, command, macros);
}

/*
 * Epics function to create a background process and execute a script
 * in that thread.
 */
epicsShareFunc int epicsShareAPI luaSpawn(const char* filename, const char* macros)
{
	luaDeprecated("luaSpawn", "luaRunFile (with option async=true)");
	return luaRunFile(filename, macros, "async=true");
}


/*
 * Epics function to load and execute a lua script file in a new
 * state, running synchronously in the calling thread. Unlike luash,
 * this compiles the entire file as a single chunk (preserving local
 * variable scope). Unlike luaSpawn, it does not create a new thread.
 */
epicsShareFunc int epicsShareAPI luaLoadFile(const char* filename, const char* macros)
{
	luaDeprecated("luaLoadFile", "luaRunFile");
	return luaRunFile(filename, macros, NULL);
}


/*
 * =========================================================================
 * Canonical run/load family (Stage 2)
 * =========================================================================
 *
 * luaRunString - run a string of Lua code as a single chunk in a new
 *                (or supplied) state, printing the final expression's
 *                result. Replaces luaCmd.
 * luaRunFile   - run a file as a single chunk in a new state. With the
 *                option "async=true" the file runs in a background
 *                thread (replacing luaSpawn); otherwise it runs
 *                synchronously (replacing luaLoadFile).
 * luaShell     - line-by-line interactive/REPL execution (replaces
 *                luash/luashLoad). Kept distinct because its per-line
 *                chunking is fundamentally different from single-chunk
 *                execution.
 *
 * All three share the (target, macros, options) argument shape. macros
 * is a key=value string applied as a scope; options is a key=value
 * string of execution-control flags parsed by luaParseOptions.
 */

/*
 * Shared file-run core. Locates 'filename', loads it as a single chunk
 * into 'state', and either spawns a background thread to run it (async)
 * or runs it synchronously in the calling thread. Takes ownership of
 * 'state' (unrefs it, or hands it to the spawned thread which unrefs).
 *
 * Returns 0 on success, -1 if the file is not found, or the nonzero
 * load/pcall status on a compile/runtime error.
 */
static int runFileState(lua_State* state, const char* filename, int async)
{
	std::string temp(filename);
	std::string found = luaLocateFile(temp);

	if (found.empty())
	{
		printf("luaRunFile: file not found: %s\n", filename);
		luaStateUnref(state);
		return -1;
	}

	int status = luaL_loadfile(state, found.c_str());

	if (status)
	{
		printf("%s\n", lua_tostring(state, -1));
		lua_pop(state, 1);
		luaStateUnref(state);
		return status;
	}

	if (async)
	{
		std::string threadname("luaRunFile:");
		threadname += filename;

		epicsThreadCreate(threadname.c_str(),
		                  epicsThreadPriorityLow,
		                  epicsThreadGetStackSize(epicsThreadStackMedium),
		                  (EPICSTHREADFUNC)::spawn_thread_callback, state);

		return 0;
	}

	status = lua_pcall(state, 0, 0, 0);

	if (status)
	{
		printf("%s\n", lua_tostring(state, -1));
		lua_pop(state, 1);
	}

	luaStateUnref(state);

	return status;
}


extern "C"
{

/*
 * Run a string of Lua code as a single chunk, printing the final
 * result. Canonical replacement for luaCmd.
 */
epicsShareFunc int epicsShareAPI luaRunString(const char* code, const char* macros, const char* options)
{
	(void) options;  /* no execution-control options defined for strings yet */

	return luaCmd(NULL, code, macros);
}

/*
 * Run a Lua file as a single chunk in a new state. With option
 * "async=true" the file runs in a background thread; otherwise it runs
 * synchronously. Canonical replacement for luaLoadFile and luaSpawn.
 */
epicsShareFunc int epicsShareAPI luaRunFile(const char* filename, const char* macros, const char* options)
{
	if (!filename || filename[0] == '\0')
	{
		printf("luaRunFile: no filename specified\n");
		return -1;
	}

	lua_State* state = luaCreateState();

	if (macros)    { luaLoadMacros(state, macros); }

	/* Parse execution-control options (async, ...) using the shared
	 * options grammar. The table is popped before running. */
	int async = 0;

	if (options)
	{
		luaParseOptions(state, options);
		async = luaOptionBool(state, lua_gettop(state), "async", 0);
		lua_pop(state, 1);
	}

	return runFileState(state, filename, async);
}

/*
 * Run a Lua script file line-by-line (REPL/interactive style),
 * echoing each line and printing each result. Canonical replacement
 * for luashLoad. Passing NULL for pathname starts an interactive
 * shell. Line-by-line execution does NOT preserve local variables
 * across lines; use luaRunFile for whole-file semantics.
 */
epicsShareFunc int epicsShareAPI luaShell(const char* pathname, const char* macros)
{
	/* Call the shell core directly (not the deprecated luashLoad) so
	 * canonical use does not emit a deprecation warning. */
	return luash(NULL, pathname, macros);
}

}


epicsShareFunc void epicsShareAPI luashSetCommonState(const char* name)
{
	epicsGuard<epicsMutex> guard(defaultStateMutex);

	if (! name)    { default_state = NULL; return; }

	default_state = luaGetState(name);
	initState(default_state);
}


static const iocshArg addPathArg0 = { "directory", iocshArgString};
static const iocshArg *addPathArgs[1] = {&addPathArg0};
static const iocshFuncDef addPathFuncDef = {"luaAddPath", 1, addPathArgs};

static void addPathCallFunc(const iocshArgBuf* args)
{
	luaAddPath(args[0].sval);
}

static const iocshArg addModuleArg0 = { "module_top", iocshArgString};
static const iocshArg *addModuleArgs[1] = {&addModuleArg0};
static const iocshFuncDef addModuleFuncDef = {"luaAddModule", 1, addModuleArgs};

static void addModuleCallFunc(const iocshArgBuf* args)
{
	luaAddModule(args[0].sval);
}

static void luashRegister(void)
{
	ensureShellStateId();
	/* Canonical commands */
	iocshRegister(&runStringFuncDef, runStringCallFunc);
	iocshRegister(&runFileFuncDef, runFileCallFunc);
	iocshRegister(&shellFuncDef, shellCallFunc);

	/* Deprecated aliases (warnings added in Stage 7) */
	iocshRegister(&luashFuncDef, luashCallFunc);
	iocshRegister(&spawnFuncDef, spawnCallFunc);
	iocshRegister(&luaCmdFuncDef, luaCmdCallFunc);
	iocshRegister(&loadFileFuncDef, loadFileCallFunc);
	iocshRegister(&addPathFuncDef, addPathCallFunc);
	iocshRegister(&addModuleFuncDef, addModuleCallFunc);
}

epicsExportRegistrar(luashRegister);
}


/*
 * Convert a Lua argument (string or table) at 'index' into a
 * key=value string. Returns an empty string if the argument is
 * absent or of another type.
 */
static std::string argToDefs(lua_State* state, int index)
{
	if (lua_istable(state, index))    { return luaMacrosFromTable(state, index); }
	if (lua_isstring(state, index))   { return std::string(lua_tostring(state, index)); }

	return std::string();
}

/*
 * Canonical Lua wrappers. Each accepts macros (arg 2) and options
 * (arg 3) as either a key=value string or a table, matching the
 * iocsh (target, macros, options) shape.
 *
 *   luaRunString("print(2+2)")
 *   luaRunFile("dev.lua", {P="dev1:"}, {async=true})
 *   luaShell("script.lua", "P=dev1:")
 */
int l_luaRunString(lua_State* state)
{
	const char* code = luaL_checkstring(state, 1);

	std::string macros  = argToDefs(state, 2);
	std::string options = argToDefs(state, 3);

	int status = luaRunString(code,
	                          macros.empty()  ? NULL : macros.c_str(),
	                          options.empty() ? NULL : options.c_str());

	if (status)
	{
		lua_pushfstring(state, "luaRunString failed (status %d)", status);
		return 1;
	}
	return 0;
}

int l_luaRunFile(lua_State* state)
{
	const char* filename = luaL_checkstring(state, 1);

	std::string macros  = argToDefs(state, 2);
	std::string options = argToDefs(state, 3);

	int status = luaRunFile(filename,
	                        macros.empty()  ? NULL : macros.c_str(),
	                        options.empty() ? NULL : options.c_str());

	if (status)
	{
		lua_pushfstring(state, "luaRunFile failed (status %d)", status);
		return 1;
	}
	return 0;
}

int l_luaShell(lua_State* state)
{
	const char* pathname = luaL_checkstring(state, 1);

	std::string macros = argToDefs(state, 2);

	int status = luaShell(pathname, macros.empty() ? NULL : macros.c_str());

	if (status)
	{
		lua_pushfstring(state, "luaShell failed (status %d)", status);
		return 1;
	}
	return 0;
}


/*
 * Lua-callable wrapper for luaSpawn that accepts either
 * a string or a table for macros.
 *
 *   luaSpawn("script.lua", "P=dev1:,PORT=SENSOR1")
 *   luaSpawn("script.lua", {P="dev1:", PORT="SENSOR1"})
 */
int l_luaSpawn(lua_State* state)
{
	const char* filename = luaL_checkstring(state, 1);

	std::string macros;

	if (lua_istable(state, 2))
	{
		macros = luaMacrosFromTable(state, 2);
	}
	else if (lua_isstring(state, 2))
	{
		macros = std::string(lua_tostring(state, 2));
	}

	int status = luaSpawn(filename, macros.empty() ? NULL : macros.c_str());

	if (status)
	{
		lua_pushfstring(state, "luaSpawn failed (status %d)", status);
		return 1;
	}
	return 0;
}

/*
 * Lua-callable wrapper for luash that accepts either
 * a string or a table for macros.
 *
 *   luash("script.lua", "P=dev1:,PORT=SENSOR1")
 *   luash("script.lua", {P="dev1:", PORT="SENSOR1"})
 */
int l_luash(lua_State* state)
{
	const char* filename = luaL_checkstring(state, 1);

	std::string macros;

	if (lua_istable(state, 2))
	{
		macros = luaMacrosFromTable(state, 2);
	}
	else if (lua_isstring(state, 2))
	{
		macros = std::string(lua_tostring(state, 2));
	}

	int status = luashLoad(filename, macros.empty() ? NULL : macros.c_str());

	if (status)
	{
		lua_pushfstring(state, "luash failed (status %d)", status);
		return 1;
	}
	return 0;
}

/*
 * Lua-callable wrapper for luaLoadFile that accepts either
 * a string or a table for macros.
 *
 *   luaLoadFile("config.lua", "P=dev1:,PORT=SENSOR1")
 *   luaLoadFile("config.lua", {P="dev1:", PORT="SENSOR1"})
 */
int l_luaLoadFile(lua_State* state)
{
	const char* filename = luaL_checkstring(state, 1);

	std::string macros;

	if (lua_istable(state, 2))
	{
		macros = luaMacrosFromTable(state, 2);
	}
	else if (lua_isstring(state, 2))
	{
		macros = std::string(lua_tostring(state, 2));
	}

	int status = luaLoadFile(filename, macros.empty() ? NULL : macros.c_str());

	if (status)
	{
		lua_pushfstring(state, "luaLoadFile failed (status %d)", status);
		return 1;
	}
	return 0;
}

/*
 * Lua-callable wrapper for luaCmd that accepts either
 * a string or a table for macros.
 *
 *   luaCmd("epicsEnvSet('K','V')", "P=dev1:")
 *   luaCmd("epicsEnvSet('K','V')", {P="dev1:"})
 */
int l_luaCmd(lua_State* state)
{
	const char* command = luaL_checkstring(state, 1);

	std::string macros;

	if (lua_istable(state, 2))
	{
		macros = luaMacrosFromTable(state, 2);
	}
	else if (lua_isstring(state, 2))
	{
		macros = std::string(lua_tostring(state, 2));
	}

	int status = luaCmd(command, macros.empty() ? NULL : macros.c_str());

	if (status)
	{
		lua_pushfstring(state, "luaCmd failed (status %d)", status);
		return 1;
	}
	return 0;
}

